### ISSUE TITLE
RenewRepo

### ISSUE THREAD

**Issue by qwgsdy** [dl1ycf/pihpsdr#27]
Hallo Christoph,

ich habe andere Pfade als du im RenewRepo angegeben hast.
Bei mir ist das Verzeichnis pihpsdr unter home/pi/github/pihpsdr.
Ich habe drei SD-Karten alle von unterschiedlichen Images erstellt.
Der Pfad ist immer gleich wie oben geschrieben.
![Screenshot_03](https://github.com/dl1ycf/pihpsdr/assets/150385654/0eebe640-9237-4b76-bf91-8d2a4ac7ef79)

Beste Grüße Roger DL2YDP

**Comment by CT1IQI** [comment]
Indeed /home/pi/github/pihpsdr
(on an Anan G2, note the slash before the home! It makes the path absolute vs. root)
When the local clone of the repository only serves to compile the current status of pihpsdr one can limit download quantity by options:
git clone -b master --single-branch --depth=1 http://github.com/dl1ycf/pihpsdr <destination folder; e.g. /home/pi/github>
This will clone a single branch without the development history.
