### ISSUE TITLE
Compile HOW TO ?

### ISSUE THREAD

**Issue by hellmind** [dl1ycf/pihpsdr#34]
Hello,

I've been trying to build this project, but I'm encountering several issues related to missing dependencies and compatibility with different versions of libraries, particularly with libgpiod. The current build process seems to require a very specific environment configuration that is not well-documented, making it challenging for new contributors to get started.

Request:

Could you please provide information on the environment where this code was successfully compiled, including details on the operating system, versions of dependencies, and any additional setup steps?

Alternatively, it would be extremely helpful if a predefined build environment (e.g., a Docker container, Vagrantfile, or virtual machine image) could be provided. This would greatly simplify the process of setting up the development environment, enabling more people to contribute without spending a lot of time troubleshooting these setup issues.

If this is not feasible, could the documentation be updated with more detailed and beginner-friendly instructions on how to compile the project? Without these improvements, it might be difficult to attract new collaborators who are willing to contribute to the project.

Thank you for considering this request, and I look forward to your response.

**Comment by dl1ycf** [comment]
It seems you have not yet read the manual. Do so before you complain.  Appendix J is where you find everything.
