### ISSUE TITLE
Add Winkey support

### ISSUE THREAD

**Issue by bouab002** [dl1ycf/pihpsdr#44]
Hello,

Some improvement that we can add to the pihpsdr.
support of winkey comport.
suport of winkey over TCPIP.
winkey serveur, listen on TCPIP.

pihpsdr have the integrated winkey like kenwood, but logging software like dxlog dose not support it.
73 de F4IRF.

**Comment by dl1ycf** [comment]
There are no plans to integrate a "WinKey clone" into pihpsdr. You can use CAT (KY) commands to generate morse (this I do in CW contests). If your logbook program does not  support that, complain there.
