### ISSUE TITLE
Hidden the dither option for Hermes Lite 2 is a really bad idea...

### ISSUE THREAD

**Issue by dl1bz** [dl1ycf/pihpsdr#45]
...because to set this bit is needed for activate the band voltage output [https://github.com/softerhardware/Hermes-Lite2/wiki/Band-Volts](https://github.com/softerhardware/Hermes-Lite2/wiki/Band-Volts
). This option is used very often by many Users for automatic band switching with PA (e.g. XPA125B) and I'm sure, they are will be not very happy about this change.

**Comment by dl1ycf** [comment]
OK, I did not know that bit of the protocol is "hi-jacked" that way (it should be mentioned in the HL2 protocol, but it is not!).
I shall add the dither bit although it does not belong in the RX menu (it should move to the RADIO menu and get a properly named check box). But if people get used to hi-jacking this check-box, OK.
